spring:



  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    url: jdbc:h2:mem:db


clevertec:
  session:
    datasource:
      url: jdbc:h2:mem:db
      username: user
      password: pass
      driver-class-name: org.h2.Driver
