CREATE TABLE IF NOT EXISTS "user"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR(50),
    name  VARCHAR(50),
    email VARCHAR(50),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_nickname UNIQUE (login)
);

CREATE TABLE user_sessions
(
    id               VARCHAR(255) NOT NULL,
    login            VARCHAR(255),
    create_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id),
    CONSTRAINT uc_user_sessions_login UNIQUE (login)
);




