spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:db
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml

clevertec:
  session:
    enable: true
    default:
      black-list: ["1", "12"]
