services:

  postgres:
    image: 'postgres:14.9'
    environment:
      - POSTGRES_DB=videohosting
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=myUser1
    ports:
      - '5432:5432'

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: my_wiremock
    ports:
      - 4444:8080
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
