services:
  postgres:
    image: 'postgres:14.9'
    environment:
      - POSTGRES_DB=videohosting
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=myUser1
    ports:
      - '5432:5432'

  minio:
    image: minio/minio:latest
    container_name: minio2
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
volumes:
  minio-data:
    driver: local
